'use strict';
/**
 * @author Herlangga Sefani {@link https://github.com/gaibz}
 * @date ${date}
 * @package ${package_name}
 * @path server/databases/migrations/${file_name}.js
 */

/** @type {import('sequelize-cli').Migration} */
// Migration name : ${migration_name}

module.exports = {
    async up(queryInterface, Sequelize) {
        // do something for migration
    },
    async down(queryInterface, Sequelize) {
        // do something to undo migration
    }

};